name: "Setup Node & pnpm"
description: "Checkout, setup Node & pnpm, install deps"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v5

    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        version: 10
        run_install: false

    - uses: actions/setup-node@v5
      with:
        node-version: 24
        cache: pnpm # ✅ built-in pnpm store caching      - run: npm install -g pnpm

    - name: "Install dependencies"
      run: pnpm install --frozen-lockfile
      shell: bash
