name: Coverage

on:
  push:
    branches: [main]

jobs:
  coverage:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - uses: actions/checkout@v5

      - uses: ./.github/actions/setup

      - name: Run coverage
        run: pnpm coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage/lcov.info
          # only needed for private repos
          token: ${{ secrets.CODECOV_TOKEN }}
